import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

/**
 * Git Automation
 */
export class GitAutomation {
  /**
   * Commit and push changes
   */
  async commitAndPush(blogTitle, files) {
    try {
      console.log('📦 Committing to Git...');

      // Add files
      for (const file of files) {
        await execAsync(`git add "${file}"`);
      }

      // Create commit
      const message = `🤖 Auto-publish: ${blogTitle}

Generated by FREE automation system
- Content: Gemini AI
- Image: Pexels
- Cost: $0.00

Published: ${new Date().toISOString()}`;

      await execAsync(`git commit -m "${message.replace(/"/g, '\\"')}"`);
      console.log('✅ Committed changes');

      // Push to GitHub
      await execAsync('git push origin main');
      console.log('✅ Pushed to GitHub');
      console.log('🚀 Netlify will deploy automatically!');

      return true;
    } catch (error) {
      console.error('❌ Git error:', error.message);
      return false;
    }
  }
}
